# Generated by Django 3.2.7 on 2021-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('Pizza_name', models.CharField(max_length=200)),
                ('Pizza_desc', models.CharField(max_length=400)),
                ('Pizza_price', models.CharField(max_length=100)),
            ],
        ),
    ]
