# Generated by Django 3.2.7 on 2021-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
