# Generated by Django 3.2.7 on 2021-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_pizza_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='Pizza_price',
            field=models.FloatField(),
        ),
    ]
