# Generated by Django 3.2.7 on 2021-09-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_pizza_pizza_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
