# Generated by Django 3.2.7 on 2021-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Pizza',
        ),
        migrations.AddField(
            model_name='orders',
            name='Pizza_desc',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='orders',
            name='Pizza_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='Pizza_price',
            field=models.FloatField(default=0),
        ),
    ]
