# Generated by Django 3.2.7 on 2021-10-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_Image',
            field=models.ImageField(blank=True, default='images/defaultuser.png', null=True, upload_to='images'),
        ),
    ]
