# Generated by Django 3.2.7 on 2021-10-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20211011_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
