# Generated by Django 3.2.7 on 2021-10-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_orders_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
